import type {
  BusinessQuery,
  BusinessStatus,
  ProductQuery,
  TalentQuery,
  TestimonialStatus,
} from '@/types/api'

/** Central query-key registry so invalidation targets stay consistent. */
export const queryKeys = {
  me: ['me'] as const,
  myVerificationDocument: ['me', 'verification-document'] as const,
  myCvDocument: ['me', 'cv-document'] as const,
  categories: ['categories'] as const,
  locations: ['locations'] as const,
  talentSkills: ['talent-skills'] as const,
  businesses: (query: BusinessQuery) => ['businesses', query] as const,
  latestBusinesses: (limit: number) => ['businesses', 'latest', limit] as const,
  publicStats: ['businesses', 'stats'] as const,
  business: (slug: string) => ['business', slug] as const,
  products: (query: ProductQuery) => ['products', query] as const,
  product: (slug: string) => ['product', slug] as const,
  talents: (query: TalentQuery) => ['talents', query] as const,
  latestTalents: (limit: number) => ['talents', 'latest', limit] as const,
  talent: (slug: string) => ['talent', slug] as const,
  myBusinesses: ['my-businesses'] as const,
  myBusiness: (id: string) => ['my-business', id] as const,
  myBusinessItems: (id: string) => ['my-business', id, 'items'] as const,
  readiness: (id: string) => ['my-business', id, 'readiness'] as const,
  myViews: ['my-views'] as const,
  myTestimonials: (id: string) => ['my-business', id, 'testimonials'] as const,
  myOrders: (id: string) => ['my-business', id, 'orders'] as const,
  myTalent: ['my-talent'] as const,
  myTalentReadiness: ['my-talent', 'readiness'] as const,
  myServiceRequests: ['my-talent', 'requests'] as const,
  adminStats: ['admin', 'stats'] as const,
  adminBusinesses: (status: BusinessStatus | undefined, page: number, q?: string) =>
    ['admin', 'businesses', status ?? 'all', page, q ?? ''] as const,
  adminBusiness: (id: string) => ['admin', 'business', id] as const,
  adminUsers: (page: number) => ['admin', 'users', page] as const,
  adminUser: (id: string) => ['admin', 'user', id] as const,
  adminCategories: ['admin', 'categories'] as const,
  adminTalents: (status: BusinessStatus | undefined, page: number, q?: string) =>
    ['admin', 'talents', status ?? 'all', page, q ?? ''] as const,
  adminTalent: (id: string) => ['admin', 'talent', id] as const,
  adminTalentSkills: ['admin', 'talent-skills'] as const,
  adminLocations: ['admin', 'locations'] as const,
  feedbackTickets: ['admin', 'feedback', 'tickets'] as const,
  feedbackTicket: (id: string) => ['admin', 'feedback', 'ticket', id] as const,
  feedbackAssignees: ['admin', 'feedback', 'assignees'] as const,
  adminTestimonials: (status: TestimonialStatus | 'ALL') =>
    ['admin', 'testimonials', status] as const,
}
