"""testimonials gain a platform review gate

``testimonial_status`` grows from three states to five. Submitted praise now
waits on the platform before it reaches the owner at all, so the initial state
is PENDING_REVIEW, the owner's queue is PENDING_OWNER, and an administrator
can refuse one outright with REJECTED.

Existing rows are mapped PENDING -> PENDING_REVIEW rather than
PENDING -> PENDING_OWNER. Those rows were submitted before the platform gate
existed and have never been reviewed, so sending them through the new gate is
the conservative reading; they were not public either way. APPROVED and HIDDEN
keep their meaning and their rows.

Written by hand rather than autogenerated. A Postgres enum cannot gain a value
and have it used in the same transaction, so this creates the new type, casts
the column across with an explicit CASE, and renames it into place — which
also makes the mapping reviewable instead of implicit.

Revision ID: 3c91d4e2f7a8
Revises: 2a7b59107832
Create Date: 2026-09-15 19:40:00.000000+00:00
"""

from __future__ import annotations

from alembic import op

revision = "3c91d4e2f7a8"
down_revision = "2a7b59107832"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        "CREATE TYPE testimonial_status_new AS ENUM "
        "('PENDING_REVIEW', 'PENDING_OWNER', 'APPROVED', 'HIDDEN', 'REJECTED')"
    )
    op.execute("ALTER TABLE testimonials ALTER COLUMN status DROP DEFAULT")
    op.execute(
        "ALTER TABLE testimonials ALTER COLUMN status TYPE testimonial_status_new "
        "USING (CASE status::text "
        "WHEN 'PENDING' THEN 'PENDING_REVIEW' "
        "ELSE status::text END)::testimonial_status_new"
    )
    op.execute("DROP TYPE testimonial_status")
    op.execute("ALTER TYPE testimonial_status_new RENAME TO testimonial_status")
    op.execute(
        "ALTER TABLE testimonials ALTER COLUMN status "
        "SET DEFAULT 'PENDING_REVIEW'::testimonial_status"
    )


def downgrade() -> None:
    """Collapses both pending states back to the single PENDING.

    REJECTED has no pre-gate equivalent: the platform could not refuse one
    before this revision, so those rows become HIDDEN — not public, and still
    visible to an administrator, which is the closest the old three states
    came to saying "kept but not shown".
    """
    op.execute("CREATE TYPE testimonial_status_old AS ENUM ('PENDING', 'APPROVED', 'HIDDEN')")
    op.execute("ALTER TABLE testimonials ALTER COLUMN status DROP DEFAULT")
    op.execute(
        "ALTER TABLE testimonials ALTER COLUMN status TYPE testimonial_status_old "
        "USING (CASE status::text "
        "WHEN 'PENDING_REVIEW' THEN 'PENDING' "
        "WHEN 'PENDING_OWNER' THEN 'PENDING' "
        "WHEN 'REJECTED' THEN 'HIDDEN' "
        "ELSE status::text END)::testimonial_status_old"
    )
    op.execute("DROP TYPE testimonial_status")
    op.execute("ALTER TYPE testimonial_status_old RENAME TO testimonial_status")
    op.execute(
        "ALTER TABLE testimonials ALTER COLUMN status "
        "SET DEFAULT 'PENDING'::testimonial_status"
    )
