"""add owner personal phone and verification document

Revision ID: 730b8921ac10
Revises: cc24c0848f3d
Create Date: 2026-09-05 00:57:11.781857+00:00
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '730b8921ac10'
down_revision = 'cc24c0848f3d'
branch_labels = None
depends_on = None


def _inspector():
    return sa.inspect(op.get_bind())


def _has_table(table: str) -> bool:
    return _inspector().has_table(table)


def _has_column(table: str, column: str) -> bool:
    if not _has_table(table):
        return False
    return column in {c["name"] for c in _inspector().get_columns(table)}


def _has_index(table: str, index: str) -> bool:
    if not _has_table(table):
        return False
    return index in {i["name"] for i in _inspector().get_indexes(table)}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if not _has_table('owner_verification_documents'):
        op.create_table('owner_verification_documents',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('storage_key', sa.String(length=500), nullable=False),
        sa.Column('content_type', sa.String(length=100), nullable=False),
        sa.Column('original_filename', sa.String(length=255), nullable=True),
        sa.Column('size_bytes', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_owner_verification_documents_user_id_users'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_owner_verification_documents'))
        )
    if not _has_index('owner_verification_documents', 'ix_owner_verification_documents_user_id'):
        op.create_index(op.f('ix_owner_verification_documents_user_id'), 'owner_verification_documents', ['user_id'], unique=True)
    if not _has_column('users', 'personal_phone_number'):
        op.add_column('users', sa.Column('personal_phone_number', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###
    # NOTE: autogenerate also proposed dropping ix_business_items_title_trgm and
    # ix_businesses_search_text_trgm. Those are real GIN trigram indexes created
    # via raw SQL in cc24c0848f3d_initial_schema.py, not declared as SQLAlchemy
    # Index objects, so autogenerate can't match them against the models and
    # flags them as "removed" — a known false positive, not an actual change.
    # Deliberately not dropped here.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'personal_phone_number')
    op.drop_index(op.f('ix_owner_verification_documents_user_id'), table_name='owner_verification_documents')
    op.drop_table('owner_verification_documents')
    # ### end Alembic commands ###
