"""add product detail fields and item gallery

Revision ID: fe5c48e66ec9
Revises: d2f6a3c81b47
Create Date: 2026-09-14 05:17:46.088477+00:00
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'fe5c48e66ec9'
down_revision = 'd2f6a3c81b47'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_item_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('caption', sa.String(length=300), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['business_items.id'], name=op.f('fk_business_item_images_item_id_business_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_business_item_images'))
    )
    op.create_index(op.f('ix_business_item_images_item_id'), 'business_item_images', ['item_id'], unique=False)
    op.create_index('ix_business_item_images_item_sort', 'business_item_images', ['item_id', 'sort_order'], unique=False)
    op.add_column('business_items', sa.Column('good_type', sa.String(length=160), nullable=True))
    op.add_column('business_items', sa.Column('brand_name', sa.String(length=160), nullable=True))
    op.add_column('business_items', sa.Column('ingredients', sa.Text(), nullable=True))
    op.add_column('business_items', sa.Column('manufactured_at', sa.Date(), nullable=True))
    op.add_column('business_items', sa.Column('expiry_date', sa.Date(), nullable=True))
    op.add_column('business_items', sa.Column('net_weight', sa.String(length=80), nullable=True))
    op.add_column('business_items', sa.Column('external_link', sa.String(length=500), nullable=True))
    # Note: autogenerate also proposed dropping the trigram GIN indexes on
    # business_items/businesses/talent_profiles search columns -- those are
    # raw-SQL indexes not tracked by SQLAlchemy metadata, so autogenerate
    # always misreads them as removed. Left untouched here deliberately.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business_items', 'external_link')
    op.drop_column('business_items', 'net_weight')
    op.drop_column('business_items', 'expiry_date')
    op.drop_column('business_items', 'manufactured_at')
    op.drop_column('business_items', 'ingredients')
    op.drop_column('business_items', 'brand_name')
    op.drop_column('business_items', 'good_type')
    op.drop_index('ix_business_item_images_item_sort', table_name='business_item_images')
    op.drop_index(op.f('ix_business_item_images_item_id'), table_name='business_item_images')
    op.drop_table('business_item_images')
    # ### end Alembic commands ###
