"""add business custom category text

Revision ID: ff08752870d6
Revises: 730b8921ac10
Create Date: 2026-09-05 01:07:02.900635+00:00
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'ff08752870d6'
down_revision = '730b8921ac10'
branch_labels = None
depends_on = None


def _inspector():
    return sa.inspect(op.get_bind())


def _has_table(table: str) -> bool:
    return _inspector().has_table(table)


def _has_column(table: str, column: str) -> bool:
    if not _has_table(table):
        return False
    return column in {c["name"] for c in _inspector().get_columns(table)}


def _has_index(table: str, index: str) -> bool:
    if not _has_table(table):
        return False
    return index in {i["name"] for i in _inspector().get_indexes(table)}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if not _has_column('businesses', 'custom_category_text'):
        op.add_column('businesses', sa.Column('custom_category_text', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###
    # NOTE: autogenerate also proposed dropping ix_business_items_title_trgm and
    # ix_businesses_search_text_trgm — the same pre-existing false positive
    # noted in 730b8921ac10 (raw-SQL GIN trigram indexes autogenerate can't
    # match against the declarative models). Deliberately not dropped here.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'custom_category_text')
    # ### end Alembic commands ###
